import {Html} from '@react-three/drei';
export const Loader = () => {
  return (
    <Html>
        <div>
            AAAAAAAAAAAAAAAAAAAAAA LOADING AAAAAAAAAAAAAAAAAAAAAA LOADING AAAAAAAAAAAAAAAAAAAAAA LOADING AAAAAAAAAAAAAAAAAAAAAA LOADING AAAAAAAAAAAAAAAAAAAAAA LOADING AAAAAAAAAAAAAAAAAAAAAA LOADING AAAAAAAAAAAAAAAAAAAAAA LOADING
        </div>
    </Html>
    
  )
}
