/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Vladimir E. (https://sketchfab.com/Room_42)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cuboctahedron-905aaa8d6406491a818dff222e2fa2b8
Title: Cuboctahedron
*/
import { useRef, useEffect, useState } from "react";
import { useGLTF } from "@react-three/drei";
import {useFrame} from '@react-three/fiber';
import cuboctahedron from '../assets/3d/shapes/cuboctahedron.glb';
import {a} from '@react-spring/three';

const Cuboctahedron = (props) => {
    const cuboRef = useRef();
    const { nodes, materials } = useGLTF(cuboctahedron);
    const [moveAway, setMoveAway] = useState(false);

    useFrame(({clock}) => {
        // Rotation animation
        cuboRef.current.rotation.x += 0.005;
        cuboRef.current.rotation.y += 0.005;
        // Moving away animation
        if (moveAway) {
            if (cuboRef.current.position.y <= -300) {
                setMoveAway(false);
                // Octahedron is in charge of switching pages!
            } else if (moveAway) {
                cuboRef.current.position.y -= Math.min(1.9**(3*(clock.elapsedTime)), 10);
                cuboRef.current.position.x += Math.min(1.9**(1.5*(clock.elapsedTime)), 10);
            }
        }
    });

    useEffect(() => {
        if (props.clicked) {
            setMoveAway(true);
            props.setClicked(false);
        }
    },[props.clicked])
    
    return (
        <a.group ref={cuboRef} {...props}>
            <mesh
                geometry={nodes.Object_2.geometry}
                material={materials["1.001"]}
                rotation={[-Math.PI / 2, 0, 0]}
                onPointerEnter={() => props.setHovered(2)}
                onPointerLeave={() => props.setHovered(0)}
            >
                <meshPhongMaterial emissive={0xFF00F7} emissiveIntensity={props.hovered == 2 ? 4 : 0}/>
            </mesh>
        </a.group>
    );
}

export default Cuboctahedron;
