export const COLORS = {
    STAT_TXT_HIGHLIGHTED: "#ffeb14",
    ALGO_TXT_HIGHLIGHTED: "#ffa8fc",
    STAT_HIGHLIGHTED: 0x59571A,
    ALGO_HIGHLIGHTED: 0xFF00F7,
    GRAPH_NODE: "#f5b5ef",
    GRAPH_NODE_HIGHLIGHTED: "red",
    ARROW: 0x949494,
    ARROW_HIGHLIGHTED: 0x0a8505,
}
